image: node:latest

# Pick zero or more services to be used on all builds.
# services:
#   - mysql:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

cache:
  paths:
  - node_modules/

before_script:
  - npm install -g yarn


stages:
  - check
  - test
  - deploy

eslint:
  stage: check
  script:
  - yarn
  - yarn run linter